AMB-783 Refactored status_monitoring code, removed hitting _status on pr

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -270,6 +270,18 @@ steps:
         export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
       fi
 
+      if [[ "${{ parameters.enable_status_monitoring }}"]]; then
+        echo "##vso[task.setvariable variable=set_status_monitoring]true"
+      else
+        echo "##vso[task.setvariable variable=set_status_monitoring]false"
+      fi
+
+      if [[ "${{ parameters.service_base_path }}" == *"-pr-"* ]]; then
+        echo "##vso[task.setvariable variable=set_status_monitoring]false"
+      else
+        echo "##vso[task.setvariable variable=set_status_monitoring]true"
+      fi
+
       echo "##vso[task.setvariable variable=url]$url"
       echo "##vso[task.setvariable variable=status_body]$status_body"
       echo "##vso[task.setvariable variable=ping_body]$ping_body"
@@ -313,42 +325,32 @@ steps:
         echo "##vso[task.setvariable variable=set_ping_monitoring]false"
       displayName: 'Set ping endpoint monitoring'
 
-  - ${{ if eq(parameters.enable_status_monitoring, true) }}:
+  - ${{ if eq(set_status_monitoring, true) }}:
     - bash: |
         set -euo pipefail
-
-        if [[ "${{ parameters.service_base_path }}" != *"-pr-"* ]]; then
-          if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
-            export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
-          else
-            export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
-          fi
+       
+        if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+          export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
+        else
+          export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
+        fi
 
           echo _status_response=$status_endpoint_response
           echo "##vso[task.setvariable variable=status_endpoint_response]$status_endpoint_response"
-        fi        
+       
+        if [[ $(status_endpoint_response) != "200" ]]; then
+          echo "##vso[task.setvariable variable=set_status_monitoring]false"
+          echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
+          exit 1            
+        fi
+        
       displayName: 'Check _status'
 
-    - bash: |
-        set -euo pipefail
-      
-        if [[ "${{ parameters.service_base_path }}" == *"-pr-"* ]]; then
-          echo "##vso[task.setvariable variable=set_status_monitoring]false"
-        else
-          if [[ $(status_endpoint_response) == "200" ]]; then
-            echo "##vso[task.setvariable variable=set_status_monitoring]true"
-          else
-            echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
-            exit 1
-          fi
-        fi
-      displayName: 'Set status endpoint monitoring'
-
-  - ${{ if eq(parameters.enable_status_monitoring, false) }}:
+  - ${{ if eq(set_status_monitoring, false) }}:
     - bash :
         echo "_status endpoint monitoring is disabled"
         echo "##vso[task.setvariable variable=set_status_monitoring]false"
-      displayName: 'Set status endpoint monitoring'
+      displayName: 'Check _status'
 
   - bash: |
       curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
