AMB-783 Changed 'if' to 'condition' syntax

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -325,32 +325,34 @@ steps:
         echo "##vso[task.setvariable variable=set_ping_monitoring]false"
       displayName: 'Set ping endpoint monitoring'
 
-  - ${{ if eq(set_status_monitoring, true) }}:
-    - bash: |
-        set -euo pipefail
-       
-        if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
-          export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
-        else
-          export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
-        fi
+ 
+  - bash: |
+      set -euo pipefail
+      
+      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+        export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
+      else
+        export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
+      fi
 
-        echo _status_response=$status_endpoint_response
-        echo "##vso[task.setvariable variable=status_endpoint_response]$status_endpoint_response"
-       
-        if [[ $(status_endpoint_response) != "200" ]]; then
-          echo "##vso[task.setvariable variable=set_status_monitoring]false"
-          echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
-          exit 1            
-        fi
-        
-      displayName: 'Check _status'
-
-  - ${{ if eq(set_status_monitoring, false) }}:
-    - bash :
-        echo "_status endpoint monitoring is disabled"
+      echo _status_response=$status_endpoint_response
+      echo "##vso[task.setvariable variable=status_endpoint_response]$status_endpoint_response"
+      
+      if [[ $(status_endpoint_response) != "200" ]]; then
         echo "##vso[task.setvariable variable=set_status_monitoring]false"
-      displayName: 'Check _status'
+        echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
+        exit 1            
+      fi
+      
+    displayName: 'Check _status'
+    condition: eq(variables['set_status_monitoring'], 'true')
+
+
+  - bash :
+      echo "_status endpoint monitoring is disabled"
+      echo "##vso[task.setvariable variable=set_status_monitoring]false"
+    displayName: 'Check _status'
+    condition: eq(variables['set_status_monitoring'], 'false')
 
   - bash: |
       curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
