AMB-783 Refactored _ping inline with _status

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -277,9 +277,9 @@ steps:
       fi
 
       if [[ "${{ parameters.enable_status_monitoring }}" == "true" ]] && [[ "${{ parameters.service_base_path }}" != *"-pr-"* ]]; then
-        echo "##vso[task.setvariable variable=set_status_monitoring]true"
+        echo "##vso[task.setvariable variable=enable_status_monitoring]true"
       else
-        echo "##vso[task.setvariable variable=set_status_monitoring]false"
+        echo "##vso[task.setvariable variable=enable_status_monitoring]false"
       fi      
 
       echo "##vso[task.setvariable variable=url]$url"
@@ -288,42 +288,26 @@ steps:
     displayName: 'Set monitoring variables'
 
 
-  - ${{ if eq(parameters.enable_monitoring, true) }}:
-    - bash: |
-        set -euo pipefail
-      
-        if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
-          export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
-        else
-          export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
-        fi
+  - bash: |
+      set -euo pipefail
+    
+      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+        export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
+      else
+        export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
+      fi
 
-        echo _ping_response=$ping_endpoint_response
-        echo "##vso[task.setvariable variable=ping_endpoint_response]$ping_endpoint_response"
-       
-      displayName: 'Check _ping'
-
-    - bash: |
-        set -euo pipefail
-      
-        if [[ "${{ parameters.service_base_path }}" == *"-pr-"* ]]; then
-          echo "##vso[task.setvariable variable=set_ping_monitoring]false"
-        else
-          if [[ $(ping_endpoint_response) == "200" ]]; then
-            echo "##vso[task.setvariable variable=set_ping_monitoring]true"
-          else
-            echo "##vso[task.logissue type=error]Your proxy doesn't have a _ping endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_monitoring=false' if your API doesn't support _ping healthcheck."
-            exit 1
-          fi
-        fi
-      displayName: 'Set ping endpoint monitoring'
-
-  - ${{ if eq(parameters.enable_monitoring, false) }}:
-    - bash :
-        echo "_ping endpoint monitoring is disabled"
+      echo _ping_response=$ping_endpoint_response
+      echo "##vso[task.setvariable variable=ping_endpoint_response]$ping_endpoint_response"
+     
+      if [[ $(ping_endpoint_response) != "200" ]]; then
         echo "##vso[task.setvariable variable=set_ping_monitoring]false"
-      displayName: 'Set ping endpoint monitoring'
-
+        echo "##vso[task.logissue type=error]Your proxy doesn't have a _ping endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_monitoring=false' if your API doesn't support _ping healthcheck."
+        exit 1       
+      fi
+      
+    displayName: 'Check _ping'
+    condition: eq(variables['parameters.enable_monitoring'], 'true')
  
   - bash: |
       set -euo pipefail
@@ -338,24 +322,24 @@ steps:
       echo "##vso[task.setvariable variable=status_endpoint_response]$status_endpoint_response"
       
       if [[ $(status_endpoint_response) != "200" ]]; then
-        echo "##vso[task.setvariable variable=set_status_monitoring]false"
+        echo "##vso[task.setvariable variable=enable_status_monitoring]false"
         echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
         exit 1            
       fi
       
     displayName: 'Check _status'
-    condition: eq(variables['set_status_monitoring'], 'true')
+    condition: eq(variables['enable_status_monitoring'], 'true')
 
   - bash: |
       curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
     displayName: Enable _status monitoring
-    condition: eq(variables['set_status_monitoring'], 'true')
+    condition: eq(variables['enable_status_monitoring'], 'true')
 
   - bash: |
       curl --fail -X 'DELETE' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
       echo "\n_status endpoint monitoring is disabled"
     displayName: Disable _status monitoring
-    condition: eq(variables['set_status_monitoring'], 'false')
+    condition: eq(variables['enable_status_monitoring'], 'false')
 
   - bash: |
       curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(ping_body)' $(url)
@@ -364,6 +348,7 @@ steps:
 
   - bash: |
       curl --fail -X 'DELETE' -H 'apikey: $(MONITORING_API_KEY)' -d '$(ping_body)' $(url)
+      echo "\n_ping endpoint monitoring is disabled"
     displayName: Disable _ping monitoring
     condition: eq(variables['set_ping_monitoring'], 'false')
 
