AMB-536 add pr check when status fails

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -292,13 +292,18 @@ steps:
           echo "##vso[task.setvariable variable=set_status_monitoring]true"
         fi
       else
-        if [[ "${{ parameters.enable_status_monitoring }}" == "false" ]]; then
-          echo "_status endpoint monitoring is disabled"
-          echo "##vso[task.setvariable variable=set_status_monitoring]false"
+        if [[ $is_pull_request ]]; then
+          echo "WARNING: Please add a _status endpoit to your proxy before releasing or your release will fail. Or use the flag 'enable_status_monitoring=false' if your API don't support _status healthcheck"          echo "##vso[task.setvariable variable=set_status_monitoring]false" 
+          echo "##vso[task.setvariable variable=set_status_monitoring]false"   
         else
-          "ERROR: Your proxy dont have a _status endpoint therefore we can't monitor this proxy therefore it should not be released"
-          exit 1
-        fi  
+          if [[ "${{ parameters.enable_status_monitoring }}" == "false" ]]; then
+            echo "_status endpoint monitoring is disabled"
+            echo "##vso[task.setvariable variable=set_status_monitoring]false"
+          else
+            echo "ERROR: Your proxy dont have a _status endpoint therefore we can't monitor this proxy therefore it should not be released"
+            exit 1
+          fi 
+        fi 
       fi
 
       if [[ $(ping_endpoint_response) == "200" ]]; then
