AMB-536 Add set-monitoring.yml

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -269,130 +269,54 @@ steps:
         echo _ping_reponse=$ping_endpoint_response
       fi
       
-      if [[ "${{ parameters.fully_qualified_service_name }}" == *"-pr-"* ]]; then
-        echo ${{ parameters.fully_qualified_service_name }}
+      if [[ "${{ parameters.service_base_path }}" == *"-pr-"* ]]; then
         export is_pull_request=true
       fi
 
       if [[ $status_endpoint_response == "200" ]]; then
         if [[ $is_pull_request ]]; then
-          echo "status endpoint is present however we dont monitor pull requests"
-          echo "##vso[task.setvariable variable=enable_status_monitoring]false"
+          echo "_status endpoint is present in the proxy, however we dont monitor pull requests"
         else
+          echo "_status endpoint is present in the proxy, we will enable monitoring by default"
           echo "##vso[task.setvariable variable=enable_status_monitoring]true"
         fi
       else
         if [[ $is_pull_request ]]; then
-          echo "WARNING: Please add a _status endpoit to your proxy before releasing"
-          echo "##vso[task.setvariable variable=enable_status_monitoring]false"
+          echo "WARNING: Please add a _status endpoit to your proxy before releasing or your release will fail. Or use the flag 'enable_status_monitoring=false' if your API don't support _status healthcheck"
         else
-          "ERROR: Your proxy dont have a _status endpoint therefore we can't monitor this proxy therefore it should not be released"
-          exit 1
+          if [[ "${{ not(parameters.enable_status_monitoring) }}" == "true" ]]; then
+            echo "_status endpoint monitoring is disabled"
+            echo "##vso[task.setvariable variable=enable_status_monitoring]false"
+          else
+            "ERROR: Your proxy dont have a _status endpoint therefore we can't monitor this proxy therefore it should not be released"
+            exit 1
+          fi
         fi
       fi
 
-      if [[  $ping_endpoint_response == "200" ]]; then
-        if [[ $is_pull_request ]]; then
-          echo "is pull request"
-          echo "##vso[task.setvariable variable=enable_ping_monitoring]false"
-        else
-          echo "##vso[task.setvariable variable=enable_ping_monitoring]true"
-        fi
-      else
-        echo "ping check fail"
-        echo "##vso[task.setvariable variable=enable_ping_monitoring]false"
-      fi
     displayName: 'Check _ping and _status endpoints'
 
-  - bash: |
-      echo "Setting stage name as snake case for monitoring"
-      export MONITORING_STAGE_NAME="${{ replace(parameters.stage_name, '_', '-') }}"
-      echo "MONITORING_STAGE_NAME=${MONITORING_STAGE_NAME}"
-      echo "##vso[task.setvariable variable=MONITORING_STAGE_NAME]$MONITORING_STAGE_NAME"
-    displayName: 'Setting MONITORING_STAGE_NAME'
+  # - ${{ if parameters.enable_monitoring }}:
+  #   - bash: |
+  #       echo "##vso[task.setvariable variable=enable_ping_monitoring]true"
 
-  - bash: |
-      echo ping monitoring $(enable_ping_monitoring)
-      echo status monitoring $(enable_status_monitoring)
-    displayName: 'debug variables'
+  # - ${{ if not(parameters.enable_monitoring) }}:
+  #   - bash: |
+  #       echo "##vso[task.setvariable variable=enable_ping_monitoring]false"
 
-  # - template: '../components/curl.yml'
-  #   condition: eq(variables['enable_ping_monitoring'], 'true')
-  #   parameters:
-  #     display_name: Add ping monitoring         
-  #     method: POST
-  #     headers: "apikey: $(MONITORING_API_KEY)"
-  #     ${{ if eq(parameters.apigee_environment, 'prod') }}:
-  #       url: "https://api.service.nhs.uk/monitoring-sd/service"
-  #       body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-  #     ${{ if not(eq(parameters.apigee_environment, 'prod')) }}:
-  #       url: "https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-  #       body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-
-  # - template: '../components/curl.yml'
-  #   condition: eq(variables['enable_status_monitoring'], 'true')
-  #   parameters:
-  #     display_name: Add status monitoring        
-  #     method: POST
-  #     headers: "apikey: $(MONITORING_API_KEY)"
-  #     ${{ if eq(parameters.apigee_environment, 'prod') }}:
-  #       url: "https://api.service.nhs.uk/monitoring-sd/service"
-  #       body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status"  ] } }'
-  #     ${{ if not(eq(parameters.apigee_environment, 'prod')) }}:
-  #       url: "https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-  #       body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status"  ] } }'
-
-  - ${{ if parameters.enable_monitoring }}:
-      - template: '../components/curl.yml'
-        parameters:
-          display_name: Add monitoring endpoints          
-          method: POST
-          headers: "apikey: $(MONITORING_API_KEY)"
-          ${{ if eq(parameters.apigee_environment, 'prod') }}:
-            url: "https://api.service.nhs.uk/monitoring-sd/service"
-            body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-          ${{ if not(eq(parameters.apigee_environment, 'prod')) }}:
-            url: "https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-            body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-
-  - ${{ if not(parameters.enable_monitoring) }}:
-      - template: '../components/curl.yml'
-        parameters:
-          display_name: Add monitoring endpoints          
-          method: DELETE
-          headers: "apikey: $(MONITORING_API_KEY)"
-          ${{ if eq(parameters.apigee_environment, 'prod') }}:
-            url: "https://api.service.nhs.uk/monitoring-sd/service"
-            body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-          ${{ if not(eq(parameters.apigee_environment, 'prod')) }}:
-            url: "https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-            body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-
-  - ${{ if parameters.enable_status_monitoring  }}:
-     - template: '../components/curl.yml'
-       parameters:
-        display_name: Add status endpoint        
-        method: POST
-        headers: "apikey: $(MONITORING_API_KEY)"
-        ${{ if eq(parameters.apigee_environment, 'prod') }}:
-          url: "https://api.service.nhs.uk/monitoring-sd/service"
-          body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
-        ${{ if not(eq(parameters.apigee_environment, 'prod')) }}:
-          url: "https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-          body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
+  # - ${{ if parameters.enable_status_monitoring }}:
+  #   - bash: | 
+  #       echo "##vso[task.setvariable variable=enable_status_monitoring]true"
 
   - ${{ if not(parameters.enable_status_monitoring) }}:
-     - template: '../components/curl.yml'
-       parameters:
-        display_name: Delete status endpoint        
-        method: DELETE
-        headers: "apikey: $(MONITORING_API_KEY)"
-        ${{ if eq(parameters.apigee_environment, 'prod') }}:
-          url: "https://api.service.nhs.uk/monitoring-sd/service"
-          body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status"  ] } }'
-        ${{ if not(eq(parameters.apigee_environment, 'prod')) }}:
-          url: "https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-          body: '{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status"  ] } }'
+    - bash: | 
+        echo "##vso[task.setvariable variable=enable_status_monitoring]false"
+
+  - template: '../components/set-monitoring.yml'
+    parameters:
+      display_name: Set monitoring         
+      enable_status_monitoring: $(enable_status_monitoring)
+      enable_ping_monitoring: $(enable_ping_monitoring)
 
   - ${{ each post_deploy_step in parameters.post_deploy }}:
     - ${{ post_deploy_step }}
