AMB-783commented out _status code

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -304,30 +304,28 @@ steps:
         echo "##vso[task.setvariable variable=enable_ping_monitoring]false"
         exit 1       
       fi 
-    displayName: 'Check _status'
+    displayName: 'Check _ping'
     condition: eq(variables['enable_ping_monitoring'], 'true')
-
  
   - bash: |
-      set -euo pipefail
+      # set -euo pipefail
       
-      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
-        export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
-      else
-        export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
-      fi
+      # if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+      #   export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
+      # else
+      #   export status_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status`
+      # fi
 
-      echo _status_response=$status_endpoint_response
-      echo "##vso[task.setvariable variable=status_endpoint_response]$status_endpoint_response"
+      # echo _status_response=$status_endpoint_response
+      # echo "##vso[task.setvariable variable=status_endpoint_response]$status_endpoint_response"
       
-      if [[ $status_endpoint_response != "200" ]]; then
-        echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
-        echo "##vso[task.setvariable variable=enable_status_monitoring]false"
-        exit 1            
-      fi     
-    displayName: 'Check _ping'
+      # if [[ $status_endpoint_response != "200" ]]; then
+      #   echo "##vso[task.logissue type=error]Your proxy doesn't have a _status endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_status_monitoring=false' if your API doesn't support _status healthcheck."
+      #   echo "##vso[task.setvariable variable=enable_status_monitoring]false"
+      #   exit 1            
+      # fi     
+    displayName: 'Check _status'
     condition: eq(variables['enable_status_monitoring'], 'true')
-
 
   - bash: |
       set -euo pipefail
