AMB-536 move curl commands to deploy-service instead of template

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -294,24 +294,94 @@ steps:
         fi
       fi
 
+      if [[ $ping_endpoint_response == "200" ]]; then
+        if [[ $is_pull_request ]]; then
+          echo "_ping endpoint is present in the proxy, however we dont monitor pull requests"
+        else
+          echo "_ping endpoint is present in the proxy, we will enable monitoring by default"
+          echo "##vso[task.setvariable variable=set_ping_monitoring]true"
+        fi
+      else
+        if [[ $is_pull_request ]]; then
+          echo "WARNING: Please add a _ping endpoit to your proxy before releasing or your release will fail."
+        else
+          if [[ "${{ not(parameters.enable_monitoring) }}" == "true" ]]; then
+            echo "_ping endpoint monitoring is disabled"
+            echo "##vso[task.setvariable variable=set_ping_monitoring]false"
+          else
+            "ERROR: Your proxy dont have a _ping endpoint therefore we can't monitor this proxy therefore it should not be released"
+            exit 1
+          fi
+        fi
+      fi
+
     displayName: 'Check _ping and _status endpoints'
 
   - ${{ if not(parameters.enable_monitoring) }}:
     - bash: |
         echo "##vso[task.setvariable variable=set_ping_monitoring]false"
+      displayName: Override set_ping_monitoring
 
   - ${{ if not(parameters.enable_status_monitoring) }}:
     - bash: | 
         echo "##vso[task.setvariable variable=set_status_monitoring]false"
+      displayName: Override set_status_monitoring
 
-  - template: '../components/set-monitoring.yml'
-    parameters:
-      set_status_monitoring: $(set_status_monitoring)
-      set_ping_monitoring: $(set_ping_monitoring)
-      stage_name: "${{ parameters.stage_name }}"
-      apigee_environment: "${{ parameters.apigee_environment }}"
-      service_name: "${{ parameters.service_name }}"
-      service_base_path: "${{ parameters.service_base_path }}"
+  - bash: |
+      echo "Setting stage name as snake case for monitoring"
+      export MONITORING_STAGE_NAME="${{ replace(parameters.stage_name, '_', '-') }}"
+      echo "MONITORING_STAGE_NAME=${MONITORING_STAGE_NAME}"
+      echo "##vso[task.setvariable variable=MONITORING_STAGE_NAME]$MONITORING_STAGE_NAME"
+    displayName: 'Setting MONITORING_STAGE_NAME'
+
+  - bash: |
+      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+        export url="https://api.service.nhs.uk/monitoring-sd/service"
+        export status_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
+        export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
+
+        echo "##vso[task.setvariable variable=url]$url"
+        echo "##vso[task.setvariable variable=status_body]$status_body"
+        echo "##vso[task.setvariable variable=ping_body]$ping_body"
+      else
+        export url="https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
+        export status_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
+        export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
+
+        echo "##vso[task.setvariable variable=url]$url"
+        echo "##vso[task.setvariable variable=status_body]$status_body"
+        echo "##vso[task.setvariable variable=ping_body]$ping_body"
+      fi
+    displayName: Setting monitoring url and body
+ 
+    - bash: |
+        curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
+      displayName: Enable _status monitoring
+      condition: eq(variables['set_status_monitoring'], 'true')
+
+    - bash: |
+        curl --fail -X 'DELETE' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
+      displayName: Disable _status monitoring
+      condition: eq(variables['set_status_monitoring'], 'false')
+
+    - bash: |
+        curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(ping_body)' $(url)
+      displayName: Enable _ping monitoring
+      condition: eq(variables['set_ping_monitoring'], 'true')
+
+    - bash: |
+        curl --fail -X 'DELETE' -H 'apikey: $(MONITORING_API_KEY)' -d '$(ping_body)' $(url)
+      displayName: Disable _ping monitoring
+      condition: eq(variables['set_ping_monitoring'], 'false')
+
+  # - template: '../components/set-monitoring.yml'
+  #   parameters:
+  #     set_status_monitoring: $(set_status_monitoring)
+  #     set_ping_monitoring: $(set_ping_monitoring)
+  #     stage_name: "${{ parameters.stage_name }}"
+  #     apigee_environment: "${{ parameters.apigee_environment }}"
+  #     service_name: "${{ parameters.service_name }}"
+  #     service_base_path: "${{ parameters.service_base_path }}"
 
   - ${{ each post_deploy_step in parameters.post_deploy }}:
     - ${{ post_deploy_step }}
