AMB-536 Add pr check for ping

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -293,7 +293,7 @@ steps:
         fi
       else
         if [[ $is_pull_request ]]; then
-          echo "WARNING: Please add a _status endpoit to your proxy before releasing or your release will fail. Or use the flag 'enable_status_monitoring=false' if your API don't support _status healthcheck"          echo "##vso[task.setvariable variable=set_status_monitoring]false" 
+          echo "WARNING: Please add a _status endpoit to your proxy before releasing or your release will fail. Or use the flag 'enable_status_monitoring=false' if your API don't support _status healthcheck" 
           echo "##vso[task.setvariable variable=set_status_monitoring]false"   
         else
           if [[ "${{ parameters.enable_status_monitoring }}" == "false" ]]; then
@@ -315,12 +315,17 @@ steps:
           echo "##vso[task.setvariable variable=set_ping_monitoring]true"
         fi
       else
-        if [[ "${{ parameters.enable_monitoring }}" == "false" ]]; then
-          echo "_ping endpoint monitoring is disabled"
+        if [[ $is_pull_request ]]; then
+          echo "WARNING: Please add a _ping endpoit to your proxy before releasing or your release will fail. 
           echo "##vso[task.setvariable variable=set_ping_monitoring]false"
         else
-          "ERROR: Your proxy dont have a _ping endpoint therefore we can't monitor this proxy therefore it should not be released"
-          exit 1
+          if [[ "${{ parameters.enable_monitoring }}" == "false" ]]; then
+            echo "_ping endpoint monitoring is disabled"
+            echo "##vso[task.setvariable variable=set_ping_monitoring]false"
+          else
+            "ERROR: Your proxy dont have a _ping endpoint therefore we can't monitor this proxy therefore it should not be released"
+            exit 1
+          fi
         fi
       fi
 
