AMB-783 refactor monitoring steps

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -252,6 +252,28 @@ steps:
       fi
     displayName: 'Deploy Proxy, Product and Spec'
 
+  - bash: |
+      set -euo pipefail
+
+      export MONITORING_STAGE_NAME="${{ replace(parameters.stage_name, '_', '-') }}"
+      echo "MONITORING_STAGE_NAME=${MONITORING_STAGE_NAME}"
+
+      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+        export url="https://api.service.nhs.uk/monitoring-sd/service"
+        export status_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
+        export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
+      else
+        export url="https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
+        export status_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
+        export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
+      fi
+
+      echo "##vso[task.setvariable variable=url]$url"
+      echo "##vso[task.setvariable variable=status_body]$status_body"
+      echo "##vso[task.setvariable variable=ping_body]$ping_body"
+    displayName: 'Set monitoring variables'
+
+
   - ${{ if eq(parameters.enable_monitoring, true) }}:
     - bash: |
         set -euo pipefail
@@ -268,35 +290,15 @@ steps:
 
     - bash: |
         set -euo pipefail
-
-        echo "Setting stage name as snake case for monitoring"
-        export MONITORING_STAGE_NAME="${{ replace(parameters.stage_name, '_', '-') }}"
-        echo "MONITORING_STAGE_NAME=${MONITORING_STAGE_NAME}"
-        echo "##vso[task.setvariable variable=MONITORING_STAGE_NAME]$MONITORING_STAGE_NAME"
       
         if [[ "${{ parameters.service_base_path }}" == *"-pr-"* ]]; then
-          export is_pull_request=true
+          echo "##vso[task.setvariable variable=set_ping_monitoring]false"
         else
-          export is_pull_request=false
-        fi
-
-        if [[ $(ping_endpoint_response) == "200" ]]; then
-          if [[ $is_pull_request == 'true' ]]; then
-            echo "_ping endpoint is present in the proxy, however we dont monitor pull requests"
-            echo "##vso[task.setvariable variable=set_ping_monitoring]false"
-          else
-            echo "_ping endpoint is present in the proxy, we will enable monitoring by default"
+          if [[ $(ping_endpoint_response) == "200" ]]; then
             echo "##vso[task.setvariable variable=set_ping_monitoring]true"
-          fi
-        else
-          if [[ $is_pull_request == 'true' ]]; then
-            echo "WARNING: Please add a _ping endpoit to your proxy before releasing or your release will fail." 
-            echo "##vso[task.setvariable variable=set_ping_monitoring]false"
           else
-            "ERROR: Your proxy dont have a _ping endpoint therefore we can't monitor this proxy and it should not be released"
+            echo "##vso[task.logissue type=error]Your proxy dont have a _ping endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_monitoring=false' if your API don't support _ping healthcheck."
             exit 1
-          fi
-        fi
       displayName: 'Set ping endpoint monitoring'
 
   - ${{ if eq(parameters.enable_monitoring, false) }}:
@@ -321,19 +323,8 @@ steps:
 
     - bash: |
         set -euo pipefail
-
-        echo "Setting stage name as snake case for monitoring"
-        export MONITORING_STAGE_NAME="${{ replace(parameters.stage_name, '_', '-') }}"
-        echo "MONITORING_STAGE_NAME=${MONITORING_STAGE_NAME}"
-        echo "##vso[task.setvariable variable=MONITORING_STAGE_NAME]$MONITORING_STAGE_NAME"
       
         if [[ "${{ parameters.service_base_path }}" == *"-pr-"* ]]; then
-          export is_pull_request=true
-        else
-          export is_pull_request=false
-        fi
-
-        if [[ $is_pull_request == 'true' ]]; then
           echo "##vso[task.setvariable variable=set_status_monitoring]false"
         else
           if [[ $(status_endpoint_response) == "200" ]]; then
@@ -343,31 +334,12 @@ steps:
             exit 1
       displayName: 'Set status endpoint monitoring'
 
-
   - ${{ if eq(parameters.enable_status_monitoring, false) }}:
     - bash :
         echo "_status endpoint monitoring is disabled"
         echo "##vso[task.setvariable variable=set_status_monitoring]false"
       displayName: 'Set status endpoint monitoring'
 
-  - bash: |
-      set -euo pipefail
-
-      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
-        export url="https://api.service.nhs.uk/monitoring-sd/service"
-        export status_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
-        export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-      else
-        export url="https://internal-dev.api.service.nhs.uk/monitoring-sd/service"
-        export status_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx_with_api_key https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_status" ] } }'
-        export ping_body='{ "${{ parameters.service_name }}": { "${{ parameters.apigee_environment }}": [ "${{ parameters.service_name }}@$(MONITORING_STAGE_NAME)=http_2xx https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping" ] } }'
-      fi
-
-      echo "##vso[task.setvariable variable=url]$url"
-      echo "##vso[task.setvariable variable=status_body]$status_body"
-      echo "##vso[task.setvariable variable=ping_body]$ping_body"
-    displayName: Set monitoring url and body
- 
   - bash: |
       curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(status_body)' $(url)
     displayName: Enable _status monitoring
