AMB-783 does not check _ping on PR

diff --git a/azure/templates/deploy-service.yml b/azure/templates/deploy-service.yml
--- a/azure/templates/deploy-service.yml
+++ b/azure/templates/deploy-service.yml
@@ -271,9 +271,9 @@ steps:
       fi
 
       if [[ "${{ parameters.enable_monitoring }}" == "true" ]] && [[ "${{ parameters.service_base_path }}" != *"-pr-"* ]]; then
-        echo "##vso[task.setvariable variable=set_ping_monitoring]true"
+        echo "##vso[task.setvariable variable=enable_ping_monitoring]true"
       else
-        echo "##vso[task.setvariable variable=set_ping_monitoring]false"
+        echo "##vso[task.setvariable variable=enable_ping_monitoring]false"
       fi
 
       if [[ "${{ parameters.enable_status_monitoring }}" == "true" ]] && [[ "${{ parameters.service_base_path }}" != *"-pr-"* ]]; then
@@ -288,25 +288,25 @@ steps:
     displayName: 'Set monitoring variables'
 
 
-  - ${{ if eq(parameters.enable_monitoring, true) }}:
-    - bash: |
-        set -euo pipefail
-      
-        if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
-          export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
-        else
-          export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
-        fi
+  - bash: |
+      set -euo pipefail
+    
+      if [[ "${{ parameters.apigee_environment }}" == "prod" ]]; then
+        export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
+      else
+        export ping_endpoint_response=`curl -s -o /dev/null -w '%{http_code}' -H "apikey: $(status-endpoint-api-key)" https://${{ parameters.apigee_environment }}.api.service.nhs.uk/${{ parameters.service_base_path }}/_ping`
+      fi
 
-        echo _ping_response=$ping_endpoint_response
-        echo "##vso[task.setvariable variable=ping_endpoint_response]$ping_endpoint_response"
-      
-        if [[ $(ping_endpoint_response) != "200" ]]; then
-          echo "##vso[task.setvariable variable=set_ping_monitoring]false"
-          echo "##vso[task.logissue type=error]Your proxy doesn't have a _ping endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_monitoring=false' if your API doesn't support _ping healthcheck."
-          exit 1       
-        fi 
-      displayName: 'Check _ping'
+      echo _ping_response=$ping_endpoint_response
+      echo "##vso[task.setvariable variable=ping_endpoint_response]$ping_endpoint_response"
+    
+      if [[ $(ping_endpoint_response) != "200" ]]; then
+        echo "##vso[task.setvariable variable=enable_ping_monitoring]false"
+        echo "##vso[task.logissue type=error]Your proxy doesn't have a _ping endpoint therefore we can't monitor this proxy and it should not be released, use the flag 'enable_monitoring=false' if your API doesn't support _ping healthcheck."
+        exit 1       
+      fi 
+    displayName: 'Check _ping'
+    condition: eq(variables['enable_ping_monitoring'], 'true')
  
   - bash: |
       set -euo pipefail
@@ -343,13 +343,13 @@ steps:
   - bash: |
       curl --fail -X 'POST' -H 'apikey: $(MONITORING_API_KEY)' -d '$(ping_body)' $(url)
     displayName: Enable _ping monitoring
-    condition: eq(variables['set_ping_monitoring'], 'true')
+    condition: eq(variables['enable_ping_monitoring'], 'true')
 
   - bash: |
       curl --fail -X 'DELETE' -H 'apikey: $(MONITORING_API_KEY)' -d '$(ping_body)' $(url)
       echo "\n_ping endpoint monitoring is disabled"
     displayName: Disable _ping monitoring
-    condition: eq(variables['set_ping_monitoring'], 'false')
+    condition: eq(variables['enable_ping_monitoring'], 'false')
 
   - ${{ each post_deploy_step in parameters.post_deploy }}:
     - ${{ post_deploy_step }}
